# Question 2

In [0]:
import pandas as pd
import numpy as np
import random
from sklearn.metrics import confusion_matrix
from sklearn.metrics import f1_score

In [0]:
train_data = pd.read_csv('/content/drive/My Drive/Datasets.zip (Unzipped Files)/Datasets/q2/train.csv',header=None)

In [4]:
train_data

0  1  2  3  4  5  6  7  8  9  10 11 12 13 14 15 16 17 18 19 20 21 22
0     e  k  s  n  f  n  a  c  b  y  e  ?  s  s  o  o  p  n  o  p  b  c  l
1     e  k  s  g  f  n  f  w  b  p  e  ?  s  s  w  w  p  w  t  p  w  s  g
2     e  b  s  g  f  n  f  w  b  w  e  ?  s  s  w  w  p  w  t  p  w  s  g
3     e  s  f  g  f  n  f  c  n  n  e  e  s  s  w  w  p  w  o  p  n  v  u
4     e  f  f  g  f  n  f  w  b  p  t  e  s  f  w  w  p  w  o  e  n  a  g
...  .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. ..
4491  p  x  y  y  f  f  f  c  b  p  e  b  k  k  n  n  p  w  o  l  h  y  g
4492  p  f  y  e  f  y  f  c  n  b  t  ?  k  k  p  w  p  w  o  e  w  v  d
4493  p  x  y  g  f  f  f  c  b  h  e  b  k  k  p  p  p  w  o  l  h  y  p
4494  p  x  y  e  f  f  f  c  n  b  t  ?  s  s  w  p  p  w  o  e  w  v  d
4495  p  b  s  b  t  n  f  c  b  g  e  b  s  s  w  w  p  w  t  p  r  v  g

[4496 rows x 23 columns]

In [0]:
# Drop column number 10
train_data= np.array(train_data)
train_d=train_data[:,1:]
train_d=np.delete(train_d,10,1)
train_l=train_data[:,0:1]

#Converting to one hot encoding
n=1
d=[]
for j in range(train_d.shape[1]):
  l=set(())
  for i in range(train_d.shape[0]):
    l.add(train_d[i][j])
  n=n+1
  f={}
  m=0
  for i in l:
    f[i]=m
    m=m+1
  d.append(f)
d[17]['c']=5
d[17]['s']=6
d[17]['z']=7
d[14]['u']=1
d[6]['d']=2
d[5]['d']=2
d[5]['n']=3
train_final_data=[]
for k in range(train_d.shape[0]):
  train=[]
  for i in range(train_d.shape[1]):
    p=[]
    for j in range(len(d[i])):
      p.append(0)
    p[d[i][train_d[k][i]]]=1
    train.extend(p)
  train_final_data.append(train)
train_d=np.array(train_final_data)
train_d=np.append(train_d,train_l,axis=1)
train_data=pd.DataFrame(train_d)

In [0]:
train_data

0   1   2   3   4   5   6   7   8    ... 111 112 113 114 115 116 117 118 119
0      0   0   1   0   0   0   0   0   1  ...   0   0   0   0   0   1   0   0   e
1      0   0   1   0   0   0   0   0   1  ...   0   0   1   0   0   0   0   0   e
2      0   0   0   0   1   0   0   0   1  ...   0   0   1   0   0   0   0   0   e
3      0   1   0   0   0   0   0   0   0  ...   0   0   0   1   0   0   0   0   e
4      0   0   0   0   0   1   0   0   0  ...   1   0   1   0   0   0   0   0   e
...   ..  ..  ..  ..  ..  ..  ..  ..  ..  ...  ..  ..  ..  ..  ..  ..  ..  ..  ..
4491   0   0   0   1   0   0   1   0   0  ...   0   0   1   0   0   0   0   0   p
4492   0   0   0   0   0   1   1   0   0  ...   0   0   0   0   1   0   0   0   p
4493   0   0   0   1   0   0   1   0   0  ...   0   0   0   0   0   0   0   1   p
4494   0   0   0   1   0   0   1   0   0  ...   0   0   0   0   1   0   0   0   p
4495   0   0   0   0   1   0   0   0   1  ...   0   0   1   0   0   0   0   0   p

[4496 rows x 120 columns]

In [0]:
# Splitting data into train and validation randomly

def train_test_split(data,test_size):
  if(isinstance(test_size,float)):
    test_size=round(test_size*len(data))
  i = data.index.tolist()
  test_indices = random.sample(population=i, k=test_size)
  test_df = data.loc[test_indices]
  train_df = data.drop(test_indices)
  return train_df,test_df

In [0]:
train_d,test_d = train_test_split(train_data,0.2)

In [0]:
#Size of train and validation data
print("Total Data Size= ",len(train_data),"\nTrain Size= ",len(train_d),"\nValidation Size= ",len(test_d))

Total Data Size=  4496 
Train Size=  3597 
Validation Size=  899


In [0]:
# Split data and label...
tr= np.array(train_d)
train_d=tr[:,0:-1]
train_l=tr[:,-1]
tr= np.array(test_d)
test_d=tr[:,0:-1]
test_l=tr[:,-1]

In [0]:
#Euclidean function
def computeEuclidean (k=5):
  m=0
  result=[]
  for j in test_d:
    m=0
    dist=[]
    for i in train_d:
      dist.append([np.linalg.norm(i-j),m])
      m=m+1
    dist=sorted(dist)
    re=[]
    for l in range(k):
      temp=train_l[dist[l][1]]
      re.append(temp)
    result.append(max(set(re), key = re.count))
  return result

In [0]:
def Manhattan(i,j):
  s=0
  for k in range(len(i)):
    s+=abs(i[k]-j[k])
  return s

In [0]:
def computeManhattan(k=5):
  m=0
  result=[]
  for j in test_d:
    m=0
    dist=[]
    for i in train_d:
      dist.append([Manhattan(i,j),m])
      m=m+1
    dist=sorted(dist)
    re=[]
    for l in range(k):
      temp=train_l[dist[l][1]]
      re.append(temp)
    result.append(max(set(re), key = re.count))
  return result

In [0]:
result=computeEuclidean()
result1=computeEuclidean(k=3)
result2=computeEuclidean(k=7)
result3=computeEuclidean(k=13)

In [0]:
acc=0.0
acc1=0.0
acc2=0.0
acc3=0.0
for i in range(len(result)):
    if result[i]==test_l[i]:
        acc+=1
    if result1[i]==test_l[i]:
        acc1+=1
    if result2[i]==test_l[i]:
        acc2+=1
    if result3[i]==test_l[i]:
        acc3+=1
print ('Accuracy for k=3: ',(acc1)/len(result)*100,'%\n')
print ('Accuracy for k=5: ',(acc)/len(result)*100,'%\n')
print ('Accuracy for k=7: ',(acc2)/len(result)*100,'%\n')
print ('Accuracy for k=13: ',(acc3)/len(result)*100,'%\n')

Accuracy for k=3:  100.0 %

Accuracy for k=5:  100.0 %

Accuracy for k=7:  100.0 %

Accuracy for k=13:  100.0 %



In [0]:
result=computeManhattan()
result1=computeManhattan(k=3)
result2=computeManhattan(k=7)
result3=computeManhattan(k=13)

In [0]:
acc=0.0
acc1=0.0
acc2=0.0
acc3=0.0
for i in range(len(result)):
    if result[i]==test_l[i]:
        acc+=1
    if result1[i]==test_l[i]:
        acc1+=1
    if result2[i]==test_l[i]:
        acc2+=1
    if result3[i]==test_l[i]:
        acc3+=1
print ('Accuracy for k=3: ',(acc1)/len(result)*100,'%\n')
print ('Accuracy for k=5: ',(acc)/len(result)*100,'%\n')
print ('Accuracy for k=7: ',(acc2)/len(result)*100,'%\n')
print ('Accuracy for k=13: ',(acc3)/len(result)*100,'%\n')

Accuracy for k=3:  100.0 %

Accuracy for k=5:  100.0 %

Accuracy for k=7:  100.0 %

Accuracy for k=13:  100.0 %



In [6]:
#Load test data and test label
test_d = pd.read_csv('/content/drive/My Drive/Datasets.zip (Unzipped Files)/Datasets/q2/test.csv',header=None)
test_l = pd.read_csv('/content/drive/My Drive/Datasets.zip (Unzipped Files)/Datasets/q2/test_labels.csv',header=None)
tr=train_data.values
train_d=tr[:,0:-1]
train_l=tr[:,-1]
test_d=np.array(test_d)
test_l=np.array(test_l)
test_d=np.delete(test_d,10,1)

#converting test to one hot encoding
train_final_data=[]
for k in range(test_d.shape[0]):
  train=[]
  for i in range(test_d.shape[1]):
    p=[]
    for j in range(len(d[i])):
      p.append(0)
    p[d[i][test_d[k][i]]]=1
    train.extend(p)
  train_final_data.append(train)
test_d=np.array(train_final_data)
print(pd.DataFrame(test_d))

     0    1    2    3    4    5    6    ...  112  113  114  115  116  117  118
0      0    0    0    0    1    0    0  ...    0    0    0    0    0    1    0
1      0    0    0    0    0    1    0  ...    0    0    0    0    1    0    0
2      0    0    1    0    0    0    0  ...    0    0    0    0    0    1    0
3      0    0    1    0    0    0    1  ...    0    0    0    0    1    0    0
4      0    0    0    0    1    0    1  ...    0    0    0    0    1    0    0
..   ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...
995    0    0    0    0    1    0    1  ...    0    0    0    1    0    0    0
996    0    0    1    0    0    0    0  ...    0    0    0    0    1    0    0
997    0    0    0    0    1    0    0  ...    0    0    0    0    1    0    0
998    0    0    1    0    0    0    0  ...    0    0    0    0    0    1    0
999    0    0    0    0    1    0    0  ...    0    0    0    0    1    0    0

[1000 rows x 119 columns]


In [10]:
#Size of train and validation data
print("Total Data Size= ",(train_data.values.shape),"\nTrain Size= ",train_d.shape,"\nTest Size= ",test_d.shape)

Total Data Size=  (4496, 120) 
Train Size=  (4496, 119) 
Test Size=  (1000, 119)


In [0]:
result=computeEuclidean(k=3)

In [12]:
acc=0.0
for i in range(len(result)):
    if result[i]==test_l[i]:
        acc+=1
print ('Accuracy=',(acc)/len(result)*100,'%')

Accuracy= 100.0 %


In [14]:
#Compute from Euclidean 
confusion_matrix(test_l,result)

array([[505,   0],
       [  0, 495]])

In [23]:
#F1 Score : Euclidean
f1_score(test_l, result,average=None)

array([1., 1.])

In [0]:
result=computeManhattan()

In [16]:
acc=0.0
for i in range(len(result)):
    if result[i]==test_l[i]:
        acc+=1
print ('Accuracy=',(acc)/len(result)*100,'%')

Accuracy= 100.0 %


In [17]:
#Compute from Manhattan 
confusion_matrix(test_l,result)

array([[505,   0],
       [  0, 495]])

In [21]:
#F1 Score : Manhattan
f1_score(test_l, result,average=None)

array([1., 1.])

In [24]:
from sklearn.neighbors import KNeighborsClassifier
neigh = KNeighborsClassifier(n_neighbors=3)
neigh.fit(train_d,train_l)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=3, p=2,
                     weights='uniform')

In [27]:
from sklearn.metrics import accuracy_score
pre=neigh.predict(test_d)
accuracy_score(test_l,pre)

1.0