# **Question 3**

In [0]:
from keras.wrappers.scikit_learn import KerasClassifier
from sklearn.model_selection import cross_val_score
from tensorflow.python.keras.models import Sequential
from tensorflow.python.keras.layers import Flatten
from tensorflow.python.keras.layers import Dense
from keras.utils import to_categorical
import warnings
from tensorflow.python.keras.layers import Input
import numpy as np

## **Load data**

In [0]:
!pip install python-mnist
from mnist import MNIST
mndata = MNIST('/content/drive/My Drive/dataset')
X_train,Y_train = mndata.load_training()
X_test,Y_test= mndata.load_testing()
X_train=np.array(X_train)
Y_train=np.array(Y_train)
X_test=np.array(X_test)
Y_test=np.array(Y_test)
X_train = X_train.reshape(60000,28,28)
X_test = X_test.reshape(10000,28,28)

In [0]:
X_train.shape

(60000, 28, 28)

## **Covert label to one hot encoding**

In [0]:
Y_train_en = to_categorical(Y_train, 10)
Y_test_en = to_categorical(Y_test, 10)
warnings.simplefilter("ignore")

In [0]:
def flattern(data):
  data_f=[]
  for i in range(data.shape[0]):
    data_f.append(data[i].flatten())
  return np.array(data_f)

In [0]:
X_train_fl=flattern(X_train)
X_test_fl=flattern(X_test)

## **MLP with 1 hidden(1000) layer, Optimizer = rmsprop**

In [0]:
model = Sequential()

model.add(Dense(1000, kernel_initializer = 'uniform', activation = 'sigmoid', input_dim = X_train_fl.shape[1]))

model.add(Dense(10,activation='softmax'))

model.compile(loss='mean_squared_error', optimizer='rmsprop', metrics=['accuracy'])

model.fit(X_train_fl,Y_train_en, epochs=100, batch_size=100)

Epoch 1/100
600/600 [==============================] - 2s 3ms/step - loss: 0.0167 - accuracy: 0.8889
Epoch 2/100
600/600 [==============================] - 2s 3ms/step - loss: 0.0093 - accuracy: 0.9392
Epoch 3/100
600/600 [==============================] - 2s 3ms/step - loss: 0.0078 - accuracy: 0.9489
Epoch 4/100
600/600 [==============================] - 2s 3ms/step - loss: 0.0071 - accuracy: 0.9535
Epoch 5/100
600/600 [==============================] - 2s 3ms/step - loss: 0.0064 - accuracy: 0.9586
Epoch 6/100
600/600 [==============================] - 2s 3ms/step - loss: 0.0060 - accuracy: 0.9616
Epoch 7/100
600/600 [==============================] - 2s 3ms/step - loss: 0.0055 - accuracy: 0.9639
Epoch 8/100
600/600 [==============================] - 2s 3ms/step - loss: 0.0054 - accuracy: 0.9650
Epoch 9/100
600/600 [==============================] - 2s 3ms/step - loss: 0.0051 - accuracy: 0.9665
Epoch 10/100
600/600 [==============================] - 2s 3ms/step - loss: 0.0049 - accura

## **Accuracy and Confusion Matrix**

In [0]:
pre = model.predict(X_test_fl)
pre_=[]
for i in pre:
  pre_.append(np.argmax(i))
pre_=np.array(pre_)
from sklearn.metrics import classification_report
from sklearn.metrics import accuracy_score

print("Accuracy : ",accuracy_score(Y_test,pre_))

print(classification_report(Y_test,pre_,labels=np.unique(Y_test)))

from sklearn.metrics import confusion_matrix
print("\n\nConfusion_Matrix")
print(confusion_matrix(Y_test,pre_))

Accuracy :  0.9774
              precision    recall  f1-score   support

           0       0.99      0.98      0.98       980
           1       0.99      0.99      0.99      1135
           2       0.98      0.98      0.98      1032
           3       0.97      0.98      0.97      1010
           4       0.98      0.98      0.98       982
           5       0.98      0.96      0.97       892
           6       0.97      0.99      0.98       958
           7       0.97      0.98      0.97      1028
           8       0.97      0.97      0.97       974
           9       0.98      0.97      0.97      1009

    accuracy                           0.98     10000
   macro avg       0.98      0.98      0.98     10000
weighted avg       0.98      0.98      0.98     10000



Confusion_Matrix
[[ 960    1    1    1    0    4    7    2    4    0]
 [   0 1123    1    2    0    0    3    0    6    0]
 [   1    1 1010    4    1    1    2    7    5    0]
 [   0    0    4  993    0    2    0    4   

## **MLP with 2 hidden layer(1000,1000) Optimizer= rmsprop**

In [0]:
model = Sequential()

model.add(Dense(1000, kernel_initializer = 'uniform', activation = 'sigmoid', input_dim = X_train_fl.shape[1]))

model.add(Dense(1000, activation = 'sigmoid'))

model.add(Dense(10,activation='softmax'))

model.compile(loss='mean_squared_error', optimizer='rmsprop', metrics=['accuracy'])

model.fit(X_train_fl,Y_train_en, epochs=100, batch_size=100)

Epoch 1/100
600/600 [==============================] - 2s 3ms/step - loss: 0.0316 - accuracy: 0.7784
Epoch 2/100
600/600 [==============================] - 2s 3ms/step - loss: 0.0089 - accuracy: 0.9410
Epoch 3/100
600/600 [==============================] - 2s 3ms/step - loss: 0.0075 - accuracy: 0.9517
Epoch 4/100
600/600 [==============================] - 2s 3ms/step - loss: 0.0066 - accuracy: 0.9573
Epoch 5/100
600/600 [==============================] - 2s 3ms/step - loss: 0.0059 - accuracy: 0.9618
Epoch 6/100
600/600 [==============================] - 2s 3ms/step - loss: 0.0054 - accuracy: 0.9647
Epoch 7/100
600/600 [==============================] - 2s 3ms/step - loss: 0.0050 - accuracy: 0.9671
Epoch 8/100
600/600 [==============================] - 2s 3ms/step - loss: 0.0048 - accuracy: 0.9691
Epoch 9/100
600/600 [==============================] - 2s 3ms/step - loss: 0.0045 - accuracy: 0.9709
Epoch 10/100
600/600 [==============================] - 2s 3ms/step - loss: 0.0042 - accura

## **Accuracy and Confusion Matrix**

In [0]:
pre = model.predict(X_test_fl)
pre_=[]
for i in pre:
  pre_.append(np.argmax(i))
pre_=np.array(pre_)
from sklearn.metrics import classification_report
from sklearn.metrics import accuracy_score

print("Accuracy : ",accuracy_score(Y_test,pre_))

print(classification_report(Y_test,pre_,labels=np.unique(Y_test)))

from sklearn.metrics import confusion_matrix
print("\n\nConfusion_Matrix")
print(confusion_matrix(Y_test,pre_))

Accuracy :  0.9809
              precision    recall  f1-score   support

           0       0.99      0.98      0.99       980
           1       0.99      0.99      0.99      1135
           2       0.98      0.98      0.98      1032
           3       0.99      0.98      0.98      1010
           4       0.98      0.98      0.98       982
           5       0.98      0.97      0.98       892
           6       0.97      0.99      0.98       958
           7       0.98      0.98      0.98      1028
           8       0.98      0.96      0.97       974
           9       0.97      0.98      0.98      1009

    accuracy                           0.98     10000
   macro avg       0.98      0.98      0.98     10000
weighted avg       0.98      0.98      0.98     10000



Confusion_Matrix
[[ 965    0    2    0    0    0    9    1    1    2]
 [   0 1128    1    0    0    3    2    1    0    0]
 [   2    0 1011    0    4    0    4    8    3    0]
 [   0    0    6  986    0    4    0    4   

## **MLP with 2 hidden layer(1000,1000) Optimizer=SGD**

In [0]:
model = Sequential()

model.add(Dense(1000, kernel_initializer = 'uniform', activation = 'sigmoid', input_dim = X_train_fl.shape[1]))

model.add(Dense(1000, activation = 'sigmoid'))

model.add(Dense(10,activation='softmax'))

model.compile(loss='mean_squared_error', optimizer='sgd', metrics=['accuracy'])

model.fit(X_train_fl,Y_train_en, epochs=100, batch_size=100)

Epoch 1/100
600/600 [==============================] - 1s 2ms/step - loss: 0.0903 - accuracy: 0.1884
Epoch 2/100
600/600 [==============================] - 1s 2ms/step - loss: 0.0859 - accuracy: 0.2675
Epoch 3/100
600/600 [==============================] - 1s 2ms/step - loss: 0.0823 - accuracy: 0.3645
Epoch 4/100
600/600 [==============================] - 2s 3ms/step - loss: 0.0786 - accuracy: 0.4411
Epoch 5/100
600/600 [==============================] - 1s 2ms/step - loss: 0.0748 - accuracy: 0.4906
Epoch 6/100
600/600 [==============================] - 2s 3ms/step - loss: 0.0710 - accuracy: 0.5319
Epoch 7/100
600/600 [==============================] - 2s 3ms/step - loss: 0.0673 - accuracy: 0.5741
Epoch 8/100
600/600 [==============================] - 1s 2ms/step - loss: 0.0638 - accuracy: 0.6205
Epoch 9/100
600/600 [==============================] - 1s 2ms/step - loss: 0.0603 - accuracy: 0.6676
Epoch 10/100
600/600 [==============================] - 1s 2ms/step - loss: 0.0570 - accura

## **Accuracy and Confusion Matrix**

In [0]:
pre = model.predict(X_test_fl)
pre_=[]
for i in pre:
  pre_.append(np.argmax(i))
pre_=np.array(pre_)
from sklearn.metrics import classification_report
from sklearn.metrics import accuracy_score

print("Accuracy : ",accuracy_score(Y_test,pre_))

print(classification_report(Y_test,pre_,labels=np.unique(Y_test)))

from sklearn.metrics import confusion_matrix
print("\n\nConfusion_Matrix")
print(confusion_matrix(Y_test,pre_))

Accuracy :  0.9238
              precision    recall  f1-score   support

           0       0.94      0.98      0.96       980
           1       0.98      0.98      0.98      1135
           2       0.92      0.89      0.90      1032
           3       0.91      0.92      0.91      1010
           4       0.92      0.94      0.93       982
           5       0.90      0.88      0.89       892
           6       0.93      0.94      0.94       958
           7       0.93      0.91      0.92      1028
           8       0.89      0.89      0.89       974
           9       0.91      0.90      0.90      1009

    accuracy                           0.92     10000
   macro avg       0.92      0.92      0.92     10000
weighted avg       0.92      0.92      0.92     10000



Confusion_Matrix
[[ 963    0    3    2    0    5    3    1    3    0]
 [   0 1111    2    5    1    1    3    1   11    0]
 [  10    0  923   18   10    2   14   17   29    9]
 [   3    0   22  926    0   19    3   16   

# **CNN**

In [0]:
from tensorflow.python.keras.layers.convolutional import Conv2D
from tensorflow.python.keras.layers.pooling import MaxPooling2D
from tensorflow.python.keras.models import Model
from tensorflow.python.keras.layers import Flatten
from tensorflow.python.keras.models import Sequential
from tensorflow.python.keras.layers  import Dense, Conv2D, Flatten

## **CNN with 2 Conv(64,32), 2 Pooling(2,2) Optimizer=Adam**

In [0]:
X_train_ = X_train.reshape(60000,28,28,1)
X_test_ = X_test.reshape(10000,28,28,1)
model = Sequential()
model.add(Conv2D(64, kernel_size=3, activation='relu', input_shape=(28,28,1)))
model.add(MaxPooling2D(pool_size=(2, 2)))
model.add(Conv2D(32, kernel_size=3, activation='relu'))
model.add(MaxPooling2D(pool_size=(2, 2)))
model.add(Flatten())
model.add(Dense(10, activation='softmax'))

model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])

model.fit(X_train_,Y_train_en, validation_data=(X_test_, Y_test_en),epochs=100, batch_size=100)

Epoch 1/100
600/600 [==============================] - 3s 5ms/step - loss: 0.5087 - accuracy: 0.9110 - val_loss: 0.1011 - val_accuracy: 0.9703
Epoch 2/100
600/600 [==============================] - 3s 4ms/step - loss: 0.0891 - accuracy: 0.9735 - val_loss: 0.0823 - val_accuracy: 0.9744
Epoch 3/100
600/600 [==============================] - 3s 4ms/step - loss: 0.0655 - accuracy: 0.9799 - val_loss: 0.0702 - val_accuracy: 0.9782
Epoch 4/100
600/600 [==============================] - 3s 4ms/step - loss: 0.0572 - accuracy: 0.9823 - val_loss: 0.0800 - val_accuracy: 0.9790
Epoch 5/100
600/600 [==============================] - 3s 4ms/step - loss: 0.0462 - accuracy: 0.9853 - val_loss: 0.0732 - val_accuracy: 0.9797
Epoch 6/100
600/600 [==============================] - 3s 4ms/step - loss: 0.0408 - accuracy: 0.9866 - val_loss: 0.0958 - val_accuracy: 0.9757
Epoch 7/100
600/600 [==============================] - 3s 4ms/step - loss: 0.0402 - accuracy: 0.9875 - val_loss: 0.0563 - val_accuracy: 0.9840

## **Accuracy and Confusion Matrix**

In [0]:
pre = model.predict(X_test_)
pre_=[]
for i in pre:
  pre_.append(np.argmax(i))
pre_=np.array(pre_)
from sklearn.metrics import classification_report
from sklearn.metrics import accuracy_score

print("Accuracy : ",accuracy_score(Y_test,pre_))

print(classification_report(Y_test,pre_,labels=np.unique(Y_test)))

from sklearn.metrics import confusion_matrix
print("\n\nConfusion_Matrix")
print(confusion_matrix(Y_test,pre_))

Accuracy :  0.988
              precision    recall  f1-score   support

           0       0.99      1.00      0.99       980
           1       0.99      0.99      0.99      1135
           2       0.99      0.98      0.99      1032
           3       0.99      0.99      0.99      1010
           4       0.99      0.99      0.99       982
           5       0.97      0.99      0.98       892
           6       1.00      0.98      0.99       958
           7       0.98      0.99      0.99      1028
           8       0.98      0.99      0.99       974
           9       0.99      0.98      0.98      1009

    accuracy                           0.99     10000
   macro avg       0.99      0.99      0.99     10000
weighted avg       0.99      0.99      0.99     10000



Confusion_Matrix
[[ 976    1    0    0    0    1    1    0    1    0]
 [   0 1126    1    2    0    1    2    1    2    0]
 [   1    3 1016    3    1    1    0    4    3    0]
 [   0    0    2  998    0    6    0    2    

## **CNN with 3 Conv(64,32,32), 3 Pooling(2,2) Optimizer=rmsprop**

In [0]:
X_train_ = X_train.reshape(60000,28,28,1)
X_test_ = X_test.reshape(10000,28,28,1)
model = Sequential()
model.add(Conv2D(64, kernel_size=3, activation='relu', input_shape=(28,28,1)))
model.add(MaxPooling2D(pool_size=(2, 2)))
model.add(Conv2D(32, kernel_size=3, activation='relu'))
model.add(MaxPooling2D(pool_size=(2, 2)))
model.add(Conv2D(32, kernel_size=3, activation='relu'))
model.add(MaxPooling2D(pool_size=(2, 2)))
model.add(Flatten())
model.add(Dense(10, activation='softmax'))

model.compile(loss='categorical_crossentropy', optimizer='rmsprop', metrics=['accuracy'])

model.fit(X_train_,Y_train_en, validation_data=(X_test_, Y_test_en),epochs=100, batch_size=100)

Epoch 1/100
600/600 [==============================] - 3s 5ms/step - loss: 0.6996 - accuracy: 0.8631 - val_loss: 0.1664 - val_accuracy: 0.9521
Epoch 2/100
600/600 [==============================] - 3s 5ms/step - loss: 0.1168 - accuracy: 0.9650 - val_loss: 0.0971 - val_accuracy: 0.9700
Epoch 3/100
600/600 [==============================] - 3s 5ms/step - loss: 0.0856 - accuracy: 0.9744 - val_loss: 0.0783 - val_accuracy: 0.9783
Epoch 4/100
600/600 [==============================] - 3s 5ms/step - loss: 0.0659 - accuracy: 0.9806 - val_loss: 0.0955 - val_accuracy: 0.9746
Epoch 5/100
600/600 [==============================] - 3s 5ms/step - loss: 0.0569 - accuracy: 0.9828 - val_loss: 0.0712 - val_accuracy: 0.9815
Epoch 6/100
600/600 [==============================] - 3s 5ms/step - loss: 0.0502 - accuracy: 0.9849 - val_loss: 0.0774 - val_accuracy: 0.9817
Epoch 7/100
600/600 [==============================] - 3s 5ms/step - loss: 0.0446 - accuracy: 0.9866 - val_loss: 0.0844 - val_accuracy: 0.9774

## **Accuracy and Confusion Matrix**

In [0]:
pre = model.predict(X_test_)
pre_=[]
for i in pre:
  pre_.append(np.argmax(i))
pre_=np.array(pre_)
from sklearn.metrics import classification_report
from sklearn.metrics import accuracy_score

print("Accuracy : ",accuracy_score(Y_test,pre_))

print(classification_report(Y_test,pre_,labels=np.unique(Y_test)))

from sklearn.metrics import confusion_matrix
print("\n\nConfusion_Matrix")
print(confusion_matrix(Y_test,pre_))

Accuracy :  0.9843
              precision    recall  f1-score   support

           0       0.99      0.99      0.99       980
           1       0.98      1.00      0.99      1135
           2       0.99      0.98      0.98      1032
           3       0.99      0.98      0.99      1010
           4       0.98      0.99      0.99       982
           5       0.99      0.98      0.98       892
           6       0.99      0.99      0.99       958
           7       0.97      0.98      0.97      1028
           8       0.99      0.99      0.99       974
           9       0.99      0.97      0.98      1009

    accuracy                           0.98     10000
   macro avg       0.98      0.98      0.98     10000
weighted avg       0.98      0.98      0.98     10000



Confusion_Matrix
[[ 966    1    0    1    3    0    3    4    0    2]
 [   0 1133    0    0    0    0    0    1    1    0]
 [   2    2 1010    2    0    0    1   14    0    1]
 [   0    2    3  992    0    5    0    7   

## **SVM with different Kernal**

### **Kernal=rbf**

In [0]:
from sklearn import svm
clf = svm.SVC()
clf.fit(X_train_fl, Y_train)

SVC(C=1.0, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='scale', kernel='rbf',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)

In [0]:
pre_ = clf.predict(X_test_fl)

from sklearn.metrics import classification_report
from sklearn.metrics import accuracy_score

print("Accuracy : ",accuracy_score(Y_test,pre_))

print(classification_report(Y_test,pre_,labels=np.unique(Y_test)))

from sklearn.metrics import confusion_matrix
print("\n\nConfusion_Matrix")
print(confusion_matrix(Y_test,pre_))

Accuracy :  0.9792
              precision    recall  f1-score   support

           0       0.98      0.99      0.99       980
           1       0.99      0.99      0.99      1135
           2       0.98      0.97      0.98      1032
           3       0.97      0.99      0.98      1010
           4       0.98      0.98      0.98       982
           5       0.99      0.98      0.98       892
           6       0.99      0.99      0.99       958
           7       0.98      0.97      0.97      1028
           8       0.97      0.98      0.97       974
           9       0.97      0.96      0.97      1009

    accuracy                           0.98     10000
   macro avg       0.98      0.98      0.98     10000
weighted avg       0.98      0.98      0.98     10000



Confusion_Matrix
[[ 973    0    1    0    0    2    1    1    2    0]
 [   0 1126    3    1    0    1    1    1    2    0]
 [   6    1 1006    2    1    0    2    7    6    1]
 [   0    0    2  995    0    2    0    5   

### **Kernal=Sigmoid**

In [0]:
clf = svm.SVC(kernel='sigmoid')
clf.fit(X_train_fl, Y_train)
pre_ = clf.predict(X_test_fl)
print("Accuracy : ",accuracy_score(Y_test,pre_))

print(classification_report(Y_test,pre_,labels=np.unique(Y_test)))

print("\n\nConfusion_Matrix")
print(confusion_matrix(Y_test,pre_))

Accuracy :  0.7759
              precision    recall  f1-score   support

           0       0.81      0.83      0.82       980
           1       0.88      0.95      0.91      1135
           2       0.75      0.75      0.75      1032
           3       0.78      0.72      0.75      1010
           4       0.78      0.85      0.81       982
           5       0.57      0.66      0.61       892
           6       0.85      0.82      0.83       958
           7       0.88      0.83      0.85      1028
           8       0.69      0.64      0.67       974
           9       0.76      0.68      0.72      1009

    accuracy                           0.78     10000
   macro avg       0.77      0.77      0.77     10000
weighted avg       0.78      0.78      0.78     10000



Confusion_Matrix
[[ 812    0   29    6    0   92   35    2    4    0]
 [   0 1073   13   15    0    3    4    1   26    0]
 [  29   44  779   25   20   15   46    6   60    8]
 [  29   10   38  725    2  120    6   14   

### **Kernal=Poly**

In [0]:
clf = svm.SVC(kernel='poly')
clf.fit(X_train_fl, Y_train)
pre_ = clf.predict(X_test_fl)
print("Accuracy : ",accuracy_score(Y_test,pre_))

print(classification_report(Y_test,pre_,labels=np.unique(Y_test)))

print("\n\nConfusion_Matrix")
print(confusion_matrix(Y_test,pre_))

Accuracy :  0.9771
              precision    recall  f1-score   support

           0       0.98      0.99      0.99       980
           1       0.97      0.99      0.98      1135
           2       0.98      0.97      0.98      1032
           3       0.98      0.97      0.98      1010
           4       0.97      0.98      0.98       982
           5       0.97      0.97      0.97       892
           6       0.98      0.98      0.98       958
           7       0.97      0.97      0.97      1028
           8       0.98      0.97      0.98       974
           9       0.97      0.96      0.97      1009

    accuracy                           0.98     10000
   macro avg       0.98      0.98      0.98     10000
weighted avg       0.98      0.98      0.98     10000



Confusion_Matrix
[[ 969    0    2    0    0    4    2    1    2    0]
 [   0 1127    2    1    0    0    3    0    2    0]
 [   6    2 1006    0    2    1    3    9    3    0]
 [   0    2    3  984    0    6    0    6   

## **Submit Format**

In [0]:
#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Tue Mar 31 19:35:15 2020

@author: kishor
"""
!pip install python-mnist
import os
os.environ["TF_CPP_MIN_LOG_LEVEL"] = "3"
import sys
from mnist import MNIST
import numpy as np
from tensorflow.python.keras.layers.convolutional import Conv2D
from tensorflow.python.keras.layers.pooling import MaxPooling2D
from tensorflow.python.keras.models import Model
from tensorflow.python.keras.layers import Flatten
from tensorflow.python.keras.models import Sequential
from tensorflow.python.keras.layers  import Dense, Conv2D, Flatten
from keras.utils import to_categorical
if __name__ == "__main__":
    file_path='/content/drive/My Drive/dataset'
    mndata = MNIST(file_path)
    X_train,Y_train = mndata.load_training()
    X_test,Y_test= mndata.load_testing()
    X_train=np.array(X_train)
    Y_train=np.array(Y_train)
    X_test=np.array(X_test)
    Y_train_en = to_categorical(Y_train, 10)
    X_train_ = X_train.reshape(60000,28,28,1)
    X_test_ = X_test.reshape(10000,28,28,1)
    model = Sequential()
    model.add(Conv2D(64, kernel_size=3, activation='relu', input_shape=(28,28,1)))
    model.add(MaxPooling2D(pool_size=(2, 2)))
    model.add(Conv2D(32, kernel_size=3, activation='relu'))
    model.add(MaxPooling2D(pool_size=(2, 2)))
    model.add(Flatten())
    model.add(Dense(10, activation='softmax'))
    model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])
    model.fit(X_train_,Y_train_en,epochs=100, batch_size=100,verbose=0)
    pre= model.predict(X_test_)
    for i in pre:
        print(np.argmax(i))

Streaming output truncated to the last 5000 lines.
9
9
8
4
1
0
6
0
9
6
8
6
1
1
9
8
9
2
3
5
5
9
4
2
1
9
4
3
9
6
0
4
0
6
0
1
2
3
4
7
8
9
0
1
2
3
4
7
8
9
0
1
2
3
4
5
6
7
8
9
8
3
4
7
8
6
3
4
0
9
7
1
9
3
8
4
7
3
0
9
1
4
5
4
6
2
0
6
2
1
1
1
1
7
2
4
7
5
2
9
4
5
8
4
2
9
7
0
0
7
5
1
1
7
6
6
6
8
2
2
7
7
4
0
2
4
2
1
8
9
6
1
0
5
9
6
9
8
0
3
0
8
3
9
6
3
0
1
2
3
4
5
6
7
0
1
2
3
4
5
6
7
8
9
0
1
2
3
4
5
6
7
8
5
4
8
7
4
7
7
3
9
8
8
3
1
5
8
2
7
4
2
1
5
4
5
5
8
6
4
4
4
1
8
7
5
5
1
8
9
1
3
6
3
3
2
2
6
9
9
6
5
5
3
3
8
1
6
5
6
8
1
9
7
6
8
3
7
4
7
0
9
0
0
3
2
9
3
0
2
0
1
0
1
0
4
0
1
0
4
7
9
6
2
6
2
2
9
9
0
1
2
3
4
5
6
7
8
9
0
1
2
3
4
5
6
7
8
9
0
1
2
3
4
5
6
7
8
9
8
0
5
6
6
0
8
0
2
3
7
9
4
7
1
9
1
7
1
4
0
0
4
1
7
5
7
1
3
3
3
1
6
9
7
4
3
0
2
5
2
6
0
8
9
4
3
5
4
8
1
5
9
0
6
4
3
6
3
3
8
1
4
7
5
7
2
2
0
0
1
7
7
9
5
9
8
9
6
8
8
2
3
6
1
2
9
8
9
5
2
6
2
4
8
4
6
5
0
1
5
6
7
8
9
0
1
2
3
4
5
6
7
8
9
0
1
2
3
4
5
6
7
8
9
7
4
2
0
9
0
1
5
8
8
0
2
7
8
4
4
6
1
0
4
5
3
9
4
2
0
5
0
1
3
2
9
1
6
0
1
1
8
0
4
7
7
6
3
6
0
7
3
5
4
2