# ***Question 5***

In [0]:
import numpy as np
import pandas as pd
from sklearn.metrics import classification_report

## **Data prepossessing**

In [2]:
df = pd.read_csv('/content/drive/My Drive/Datasets/Question-5/Train(1).csv')
text=df['text']
label=df['author']
print(df)

       Unnamed: 0                                               text author
0               0  The sight of the military restored hope to tho...    MWS
1               1  Just as the building was wiped out by a German...    HPL
2               2                    Do you wonder how it will seem?    HPL
3               3  My revenge is of no moment to you; yet, while ...    MWS
4               4  If he dares to reply, you can tell him from Lu...    EAP
...           ...                                                ...    ...
15658       15658                         Get bald, too, very young.    HPL
15659       15659  I performed the first part of my journey on ho...    MWS
15660       15660  He had a narrow head, bulging, watery blue eye...    HPL
15661       15661  There does not exist the man in England with a...    MWS
15662       15662  "Every man," he said, "dreams about something,...    MWS

[15663 rows x 3 columns]


In [0]:
text=text.values
label=label.values


In [0]:
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.preprocessing import normalize
vectorizer = TfidfVectorizer()
tf_idf_vectorizor = TfidfVectorizer(stop_words = 'english',strip_accents='unicode')
tf_idf=tf_idf_vectorizor.fit_transform(text)
# print(tf_idf.shape)
# tf_idf_norm = normalize(tf_idf)
# vec=tf_idf_norm.toarray()
vec = tf_idf

## **Split into train and validation**

In [5]:
print(vec.shape,label.shape)
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test= train_test_split(vec,label,test_size=0.1,random_state=42)

(15663, 22741) (15663,)


**LinearSVC**

In [6]:
from sklearn.svm import LinearSVC
clf=LinearSVC()
clf.fit(X_train,y_train)
prediction=clf.predict(X_test)
pred_labels=prediction==y_test
acc=0.0
for i in pred_labels:
    if i==True:
        acc+=1
print ('SVM accuracy=',(acc)/len(pred_labels)*100,'%')



SVM accuracy= 79.64262922782387 %


**F1 Score:**

In [9]:

from sklearn.metrics import f1_score

print(f1_score(y_test,prediction,average='macro'))

0.7940059553539983


**Confusion_Matrix**

In [10]:
from sklearn.metrics import confusion_matrix

print(confusion_matrix(y_test,prediction))

[[540  48  71]
 [ 68 306  31]
 [ 73  28 402]]


**SGDClassifier**

In [15]:
from sklearn import linear_model
clf=linear_model.SGDClassifier(max_iter=1000, tol=1e-3,n_jobs=-1)
clf.fit(X_train,y_train)
prediction=clf.predict(X_test)
pred_labels=prediction==y_test
acc=0.0
for i in pred_labels:
    if i==True:
        acc+=1
print ('SVM accuracy=',(acc)/len(pred_labels)*100,'%')

SVM accuracy= 80.21697511167837 %


**SVM with different value of C**

In [11]:
from sklearn.svm import SVC
C_=[0.001,0.01,0.1,1,10]
for i in C_:
  clf = SVC(gamma='auto',kernel='linear',C=i)
  clf.fit(X_train,y_train)
  prediction=clf.predict(X_test)
  pred_labels=prediction==y_test
  acc=0.0
  for j in pred_labels:
      if j==True:
          acc+=1
  print ("C=",i,' SVM accuracy=',(acc)/len(pred_labels)*100,'%\n\n')
  print(classification_report(y_test,prediction,labels=np.unique(prediction)))

C= 0.001  SVM accuracy= 42.05488194001276 %


              precision    recall  f1-score   support

         EAP       0.42      1.00      0.59       659

   micro avg       0.42      1.00      0.59       659
   macro avg       0.42      1.00      0.59       659
weighted avg       0.42      1.00      0.59       659

C= 0.01  SVM accuracy= 42.05488194001276 %


              precision    recall  f1-score   support

         EAP       0.42      1.00      0.59       659

   micro avg       0.42      1.00      0.59       659
   macro avg       0.42      1.00      0.59       659
weighted avg       0.42      1.00      0.59       659

C= 0.1  SVM accuracy= 60.6892150606254 %


              precision    recall  f1-score   support

         EAP       0.52      0.98      0.68       659
         HPL       0.87      0.27      0.41       405
         MWS       0.92      0.39      0.55       503

    accuracy                           0.61      1567
   macro avg       0.77      0.55      0.55     

**SVM different Kernal**

In [13]:
from sklearn.svm import SVC
C_=['linear','poly','sigmoid','rbf']
for i in C_:
  clf = SVC(kernel=i,C=1)
  clf.fit(X_train,y_train)
  prediction=clf.predict(X_test)
  pred_labels=prediction==y_test
  acc=0.0
  for j in pred_labels:
      if j==True:
          acc+=1
  print ("Kernal= ",i,' SVM accuracy=',(acc)/len(pred_labels)*100,'%\n\n')
  print(classification_report(y_test,prediction,labels=np.unique(prediction)))

Kernal=  linear  SVM accuracy= 79.83407785577536 %


              precision    recall  f1-score   support

         EAP       0.78      0.84      0.81       659
         HPL       0.81      0.75      0.78       405
         MWS       0.82      0.78      0.80       503

    accuracy                           0.80      1567
   macro avg       0.80      0.79      0.80      1567
weighted avg       0.80      0.80      0.80      1567

Kernal=  poly  SVM accuracy= 46.58583280153159 %


              precision    recall  f1-score   support

         EAP       0.44      0.98      0.61       659
         HPL       0.78      0.05      0.10       405
         MWS       0.85      0.12      0.21       503

    accuracy                           0.47      1567
   macro avg       0.69      0.39      0.31      1567
weighted avg       0.66      0.47      0.35      1567

Kernal=  sigmoid  SVM accuracy= 79.89789406509253 %


              precision    recall  f1-score   support

         EAP       0.78  