#**Question 6**

In [0]:
import numpy as np
import glob
import statistics
import string
import math
import os
from scipy.spatial import distance

**Import all file through glob**

In [0]:
file=glob.glob('/content/drive/My Drive/Datasets/Question-6/dataset/*.txt')

**Extract label from file name**

In [0]:
label=[]
for i in file:
  ii=i.split("/content/drive/My Drive/Datasets/Question-6/dataset/")
  ii=ii[1]
  ii=ii.split(".txt")
  ii=ii[0]
  ii=ii.split("_")
  label.append(int(str(ii[1]).split()[0]))

**Data prepossessing through TfidfVectorizer**

In [15]:
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.preprocessing import normalize
vectorizer = TfidfVectorizer()
c=1
list1=[]
for i in file:
  f=open(i,"rb")
  k=f.read().decode(errors='replace')
  k = k.replace('\n', ' ')
  k = k.strip('\t')
  f.close()
  k = k.translate(str.maketrans('', '', string.punctuation))
  k = k.lower()
  list1.append(k)
  c+=1
train=np.array(list1)
tf_idf_vectorizor = TfidfVectorizer(stop_words = 'english',strip_accents='unicode')
tf_idf=tf_idf_vectorizor.fit_transform(train)
print(tf_idf.shape)
tf_idf_norm = normalize(tf_idf)
vec=tf_idf_norm.toarray()
X_train=np.asarray(vec,dtype=np.float64)
label=np.asarray(label,dtype=np.float64)

(1735, 30435)


# **Random Centroid Initialize** 

In [16]:
k_clusters = 5
k_means = np.random.uniform(size=(k_clusters,X_train.shape[1]))
for row in range(k_clusters):
    k_means[row,:] /= np.linalg.norm(k_means[row,:])
k_means.shape
np.linalg.norm(k_means,axis=1)
mean=k_means.copy()
mean=np.asarray(mean,dtype=np.float64)
old_mean=np.zeros([X_train.shape[1]])
print(mean)

[[0.00125086 0.00123563 0.00042361 ... 0.00245043 0.00551353 0.00899769]
 [0.00263968 0.00614764 0.0050626  ... 0.00484575 0.00628862 0.00257506]
 [0.00763828 0.0036311  0.00439093 ... 0.00571492 0.00140788 0.00082786]
 [0.00517997 0.00622296 0.00031951 ... 0.00555873 0.00472818 0.00181504]
 [0.00284018 0.00821176 0.00141627 ... 0.00774598 0.00158713 0.00257392]]


## **K-Mean Algo**

In [0]:
flag=True
start = 0
end = 30
list2=[]
list1={}
while start < end :
  list2=[]
  list1=[]
  for i in range(5):
    list2.append([])
    list1.append([])
  kk=1
  for i in range(X_train.shape[0]):
    temp=[]
    for j in range(mean.shape[0]):
      temp.append(distance.euclidean(X_train[i],mean[j]))
    index= temp.index(min(temp))
    list2[index].append(X_train[i])
    list1[index].append(i)
  kk+=1
  for p in range(mean.shape[0]):
    sum=np.zeros([X_train.shape[1]])
    sum=np.asarray(sum,dtype=np.float64)
    for ind in list2[p]:
      sum=sum+ind
    mean[p]=sum/len(list2[p])
  start+=1
  if(flag):
    flag = False
  else:
    count=0
    for i in range(5):
      if(np.sum(mean[i])==old_mean[i]):
        count+=1
      old_mean[i]=np.sum(mean[i])
    if(count==5):
      break

In [0]:
l=np.zeros([X_train.shape[0]])
for i in range(len(list1)):
  for j in list1[i]:
    l[j]=i

**Finding homogeneity_score**

In [14]:
from sklearn.metrics.cluster import homogeneity_score
homogeneity_score(label,l)

0.7817833303645714